[[language]]
name = "go"
roots = ["go.work", "go.mod"]
formatter = { command = "goimports" }

[[language]]
name = "typescript"
formatter = { command = 'biome', args = [
  "format",
  "--stdin-file-path",
  "buffer.ts",
] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "tsx"
formatter = { command = 'biome', args = [
  "format",
  "--stdin-file-path",
  "buffer.tsx",
] }
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
  "emmet-ls",
]

[[language]]
name = "javascript"
formatter = { command = 'biome', args = [
  "format",
  "--stdin-file-path",
  "buffer.js",
] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "jsx"
formatter = { command = 'biome', args = [
  "format",
  "--stdin-file-path",
  "buffer.jsx",
] }
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
  "emmet-ls",
]

[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "google-java-format", args = ["-"] }
language-servers = ["jdtls"]

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
language-servers = ["vscode-html-language-server", "tailwindcss-ls", "emmet-ls"]

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "nu"
formatter = { command = "nufmt", args = ["--stdin"] }

[[language]]
name = "typst"
formatter = { command = "typstyle" }

[[language]]
name = "yaml"
file-types = ["yml", "yaml"]
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "github-actions"
scope = ".github"
file-types = [
  { glob = ".github/workflows/*.yml" },
  { glob = ".github/workflows/*.yaml" },
]
formatter = { command = "prettier", args = ["--parser", "yaml"] }
language-servers = ["gh-actions-language-server", "yaml-language-server"]
roots = [".github", ".git"]

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
language-servers = ["marksman", "mdpls"]

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "jsonc"
formatter = { command = 'prettier', args = ["--parser", "jsonc"] }

[[language]]
name = "dockerfile"
language-servers = ["docker-language-server"]

[[language]]
name = "sql"
language-servers = ["sql-language-server"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "sqlformat", args = [
  "--reindent",
  "--indent_width",
  "4",
  "--keywords",
  "upper",
  "--identifiers",
  "lower",
  "-",
] }

[language-server.gopls.config]
gofumpt = true

[language-server.nu]
command = "nu"
args = ["--lsp"]

[language-server.docker-language-server]
command = "docker-language-server"
args = ["start"]

[language-server.gh-actions-language-server]
command = "gh-actions-language-server"
args = ["--stdio"]
config = { sessionToken = "" }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[language-server.mdpls]
command = "mdpls"
config = { markdown.preview.auto = true }

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

[language-server.jdtls]
command = "jdtls"
args = ["-data", "~/.cache/jdtls/workspace"]
