[[language]]
name = "go"
roots = ["go.work", "go.mod"]
formatter = { command = "goimports" }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
  "emmet-ls",
]

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "jsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
  "emmet-ls",
]

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
language-servers = ["vscode-html-language-server", "tailwindcss-ls", "emmet-ls"]

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "nu"
formatter = { command = "nufmt", args = ["--stdin"] }

[[language]]
name = "typst"
formatter = { command = "typstyle" }

[[language]]
name = "yaml"
file-types = ["yml", "yaml"]
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "github-actions"
scope = ".github"
file-types = [
  { glob = ".github/workflows/*.yml" },
  { glob = ".github/workflows/*.yaml" },
]
formatter = { command = "prettier", args = ["--parser", "yaml"] }
language-servers = ["gh-actions-language-server", "yaml-language-server"]
roots = [".github", ".git"]

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "jsonc"
formatter = { command = 'prettier', args = ["--parser", "jsonc"] }

[[language]]
name = "dockerfile"
language-servers = ["docker-language-server"]


[language-server.gopls.config]
gofumpt = true

[language-server.nu]
command = "nu"
args = ["--lsp"]

[language-server.docker-language-server]
command = "docker-language-server"
args = ["start"]

[language-server.gh-actions-language-server]
command = "gh-actions-language-server"
args = ["--stdio"]
config = { sessionToken = "" }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]
